"""Set last_modified on authored Fern documentation from Git.

Walks MDX pages under fern/docs/pages and writes each page's
last_modified frontmatter field. The generated glossary is skipped
because scripts/generate_glossary.py owns that page.

Untracked files and tracked files with substantive uncommitted
changes use today's date. A change only to last_modified does not
count. Otherwise the date is the latest commit that changed the file.

Update last_modified:

    uv run python -m rag_service.commands.documentation.update_last_modified

Check whether a page has a stale last_modified without modifying files:

    uv run python -m rag_service.commands.documentation.update_last_modified --check
"""

from __future__ import annotations

import argparse
import re
import subprocess
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[4]

PAGES_DIR = REPO_ROOT / "fern" / "docs" / "pages"

# The glossary is generated by scripts/generate_glossary.py and is
# intentionally not modified by this command.
GENERATED_GLOSSARY_PATH = (
    PAGES_DIR / "reference" / "glossary.mdx"
)

LAST_MODIFIED_PATTERN = re.compile(
    r"(?m)^last_modified:\s*.*$"
)


class LastModifiedError(ValueError):
    """Raised when last_modified metadata cannot be generated."""


def git_last_modified_date(
    path: Path,
    *,
    repo_root: Path = REPO_ROOT,
) -> str:
    """Return the Git-derived last-modified date for a file.

    Untracked files and tracked files with substantive uncommitted
    changes use today's date.

    A change only to the generated last_modified field does not count
    as a substantive content change.
    """
    resolved_root = repo_root.resolve()
    resolved_path = path.resolve()

    try:
        relative_path = resolved_path.relative_to(
            resolved_root
        )
    except ValueError as exc:
        raise LastModifiedError(
            f"{path} is outside the repository."
        ) from exc

    relative = relative_path.as_posix()

    tracked = subprocess.run(
        [
            "git",
            "ls-files",
            "--error-unmatch",
            "--",
            relative,
        ],
        cwd=resolved_root,
        capture_output=True,
        text=True,
    )

    if tracked.returncode != 0:
        return date.today().isoformat()

    diff = subprocess.run(
        [
            "git",
            "diff",
            "--quiet",
            "--ignore-matching-lines="
            "^last_modified:[[:space:]]*",
            "HEAD",
            "--",
            relative,
        ],
        cwd=resolved_root,
    )

    if diff.returncode == 1:
        return date.today().isoformat()

    if diff.returncode != 0:
        raise LastModifiedError(
            f"Could not inspect Git changes for {relative}."
        )

    history = subprocess.run(
        [
            "git",
            "log",
            "-1",
            "--format=%cs",
            "--",
            relative,
        ],
        cwd=resolved_root,
        check=True,
        capture_output=True,
        text=True,
    )

    value = history.stdout.strip()

    if not value:
        raise LastModifiedError(
            f"No Git history found for {relative}."
        )

    return value


def latest_git_date(
    paths: list[Path],
    *,
    repo_root: Path = REPO_ROOT,
) -> str:
    """Return the newest Git-derived date among source files."""
    if not paths:
        raise LastModifiedError(
            "At least one source path is required."
        )

    return max(
        git_last_modified_date(
            path,
            repo_root=repo_root,
        )
        for path in paths
    )


def render_last_modified(
    text: str,
    last_modified: str,
) -> str:
    """Insert or replace last_modified in MDX frontmatter."""
    if not text.startswith("---\n"):
        raise LastModifiedError(
            "MDX file is missing YAML frontmatter."
        )

    closing = text.find("\n---", 4)

    if closing == -1:
        raise LastModifiedError(
            "MDX frontmatter is not closed with '---'."
        )

    frontmatter = text[:closing]
    remainder = text[closing:]

    if LAST_MODIFIED_PATTERN.search(frontmatter):
        updated = LAST_MODIFIED_PATTERN.sub(
            f"last_modified: {last_modified}",
            frontmatter,
        )
    else:
        updated = (
            frontmatter
            + f"\nlast_modified: {last_modified}"
        )

    return updated + remainder


def expected_page_content(path: Path) -> str:
    """Return a page with its expected last_modified value."""
    text = path.read_text(encoding="utf-8")

    expected_date = git_last_modified_date(path)

    return render_last_modified(
        text,
        expected_date,
    )


def update_page(path: Path) -> bool:
    """Update last_modified and return whether the file changed."""
    original = path.read_text(encoding="utf-8")
    updated = expected_page_content(path)

    if original == updated:
        return False

    path.write_text(
        updated,
        encoding="utf-8",
    )

    return True


def authored_pages() -> list[Path]:
    """Return authored Fern MDX pages."""
    return [
        path
        for path in sorted(PAGES_DIR.rglob("*.mdx"))
        if path.resolve()
        != GENERATED_GLOSSARY_PATH.resolve()
    ]


def check_pages(paths: list[Path]) -> list[str]:
    """Return errors for stale last_modified metadata."""
    errors: list[str] = []

    for path in paths:
        original = path.read_text(encoding="utf-8")

        try:
            expected = expected_page_content(path)
        except LastModifiedError as exc:
            errors.append(f"{path}: {exc}")
            continue

        if original != expected:
            expected_date = git_last_modified_date(path)

            errors.append(
                f"{path}: last_modified is out of date; "
                f"expected {expected_date}."
            )

    return errors


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Check last_modified values without "
            "modifying files."
        ),
    )

    args = parser.parse_args()

    pages = authored_pages()

    if args.check:
        errors = check_pages(pages)

        if errors:
            print("last_modified validation failed:\n")

            for error in errors:
                print(f"- {error}")

            print(
                "\nRun this command to update the pages:\n"
                "uv run python -m "
                "rag_service.commands.documentation."
                "update_last_modified"
            )

            return 1

        print(
            "last_modified metadata is current for "
            f"{len(pages)} authored page(s)."
        )
        return 0

    changed = 0

    for path in pages:
        if update_page(path):
            changed += 1
            print(
                "Updated: "
                f"{path.relative_to(REPO_ROOT)}"
            )

    print(
        f"Checked {len(pages)} authored page(s); "
        f"updated {changed}."
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())