from copy import deepcopy

from rag_service.models.canonical_document import CanonicalDocument
from rag_service.models.chunk import DocumentChunk
from rag_service.processing.identifiers import ChunkIdFactory, StableChunkIdFactory
from rag_service.processing.models import ChunkContent


def build_document_chunks(
    document: CanonicalDocument,
    chunks: list[ChunkContent],
    *,
    chunk_id_factory: ChunkIdFactory | None = None,
) -> list[DocumentChunk]:
    """Attach document and chunk metadata to ordered chunk content.

    Stable, content-addressed IDs are generated by default. A custom factory
    can be injected for tests or an alternative identifier strategy.
    """

    document_chunks: list[DocumentChunk] = []
    seen_chunk_ids: set[str] = set()
    id_factory = chunk_id_factory or StableChunkIdFactory()

    for sequence, chunk in enumerate(chunks):
        chunk_id = id_factory(document, chunk, sequence)

        if not chunk_id:
            raise ValueError("chunk_id_factory returned an empty chunk ID")
        if chunk_id in seen_chunk_ids:
            raise ValueError(f"chunk_id_factory returned duplicate ID: {chunk_id}")
        seen_chunk_ids.add(chunk_id)

        document_chunks.append(
            DocumentChunk(
                chunk_id=chunk_id,
                document_id=document.document_id,
                source=document.source,
                source_id=document.source_id,
                title=document.title,
                url=document.url,
                content_type=document.content_type,
                text=chunk.text,
                heading_path=list(chunk.heading_path),
                sequence=sequence,
                block_types=_unique_block_types(chunk),
                block_metadata=_block_metadata(chunk),
                anchor=chunk.anchor,
                metadata=deepcopy(document.metadata),
                published_at=document.published_at,
                modified_at=document.modified_at,
            )
        )

    return document_chunks


def _unique_block_types(chunk: ChunkContent) -> list[str]:
    return list(dict.fromkeys(block.block_type for block in chunk.blocks))


def _block_metadata(chunk: ChunkContent) -> list[dict[str, object]]:
    return [
        {
            **deepcopy(block.metadata),
            "block_type": block.block_type,
        }
        for block in chunk.blocks
        if block.metadata
    ]
