#!/usr/bin/env python3
"""Generate the public glossary page and Vale vocabulary from glossary.yml.

Reads docs/data/glossary.yml, checks every term, then writes two generated
files. Do not edit those files by hand.

Run after editing the glossary source:
    # Regenerate
    uv run python scripts/generate_glossary.py
    # Validate only; change nothing
    uv run python scripts/generate_glossary.py --check

Steps:

1. Load docs/data/glossary.yml.
2. Validate the source before generating anything:
   - version must match the schema this script supports
   - each term needs id, term, and definition
   - ids are unique lowercase kebab-case (example: hybrid-search)
   - canonical terms are unique and start with a letter
   - aliases are unique within a term
   - related_terms must point at real ids, not the term itself
3. Stop with errors and write nothing if validation fails.
4. Sort terms A–Z and build the glossary page:
   - letter headings
   - definition; and optional example, aliases and related-term links
5. Collect canonical terms plus aliases for the Vale vocabulary.
6. Write both files and print what was generated:
   - fern/docs/pages/reference/glossary.mdx
   - styles/config/vocabularies/RAGService/accept.txt
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]

SOURCE_PATH = REPO_ROOT / "docs" / "data" / "glossary.yml"

GLOSSARY_PATH = (
    REPO_ROOT
    / "fern"
    / "docs"
    / "pages"
    / "reference"
    / "glossary.mdx"
)

VALE_ACCEPT_PATH = (
    REPO_ROOT
    / "styles"
    / "config"
    / "vocabularies"
    / "RAGService"
    / "accept.txt"
)

SUPPORTED_VERSION = 1

ID_PATTERN = re.compile(r"^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$")

GENERATED_NOTE = (
    "{/*GENERATED FILE. Source: docs/data/glossary.yml. "
    "Do not edit this file directly.*/}"
)


@dataclass(frozen=True)
class GlossaryTerm:
    id: str
    term: str
    definition: str
    example: str | None = None
    aliases: tuple[str, ...] = ()
    related_terms: tuple[str, ...] = ()


class GlossaryValidationError(ValueError):
    """Raised when glossary.yml does not satisfy the glossary contract."""

    def __init__(self, errors: list[str]) -> None:
        super().__init__("\n".join(errors))
        self.errors = errors


def load_glossary(path: Path) -> list[GlossaryTerm]:
    """Load and validate glossary.yml."""
    if not path.is_file():
        raise FileNotFoundError(f"Glossary source not found: {path}")

    with path.open(encoding="utf-8") as handle:
        data = yaml.safe_load(handle)

    errors: list[str] = []

    if not isinstance(data, dict):
        raise GlossaryValidationError(
            ["Glossary source must contain a top-level mapping."]
        )

    if data.get("version") != SUPPORTED_VERSION:
        errors.append(
            f"'version' must be {SUPPORTED_VERSION}; "
            f"found {data.get('version')!r}."
        )

    raw_terms = data.get("terms")
    if not isinstance(raw_terms, list):
        errors.append("'terms' must be a list.")
        raise GlossaryValidationError(errors)

    terms: list[GlossaryTerm] = []
    seen_ids: dict[str, str] = {}
    seen_terms: dict[str, str] = {}

    for index, raw_term in enumerate(raw_terms, start=1):
        label = f"Term #{index}"

        if not isinstance(raw_term, dict):
            errors.append(f"{label}: entry must be a mapping.")
            continue

        term_id = _required_string(
            raw_term,
            "id",
            label,
            errors,
        )
        term = _required_string(
            raw_term,
            "term",
            label,
            errors,
        )
        definition = _required_string(
            raw_term,
            "definition",
            label,
            errors,
        )

        if term:
            label = f'Term "{term}"'

        example = _optional_string(
            raw_term,
            "example",
            label,
            errors,
        )
        aliases = _string_list(
            raw_term,
            "aliases",
            label,
            errors,
        )
        related_terms = _string_list(
            raw_term,
            "related_terms",
            label,
            errors,
        )

        if term_id:
            if not ID_PATTERN.fullmatch(term_id):
                errors.append(
                    f"{label}: id {term_id!r} must use "
                    "lowercase kebab-case."
                )

            if term_id in seen_ids:
                errors.append(
                    f"{label}: duplicate id {term_id!r}; "
                    f"already used by {seen_ids[term_id]!r}."
                )
            else:
                seen_ids[term_id] = term or label

        if term:
            normalized_term = term.casefold()

            if normalized_term in seen_terms:
                errors.append(
                    f"{label}: duplicate canonical term; "
                    f"already used by "
                    f"{seen_terms[normalized_term]!r}."
                )
            else:
                seen_terms[normalized_term] = term

            if not re.match(r"^[A-Za-z]", term):
                errors.append(
                    f"{label}: canonical term must begin "
                    "with a letter in schema version 1."
                )

        if aliases:
            seen_aliases: set[str] = set()

            for alias in aliases:
                normalized_alias = alias.casefold()

                if normalized_alias in seen_aliases:
                    errors.append(
                        f"{label}: duplicate alias {alias!r}."
                    )

                seen_aliases.add(normalized_alias)

        if term_id and term and definition:
            terms.append(
                GlossaryTerm(
                    id=term_id,
                    term=term,
                    definition=definition,
                    example=example,
                    aliases=tuple(aliases),
                    related_terms=tuple(related_terms),
                )
            )

    ids = {entry.id for entry in terms}

    for entry in terms:
        for related_id in entry.related_terms:
            if related_id == entry.id:
                errors.append(
                    f'Term "{entry.term}": related_terms '
                    "cannot reference itself."
                )
            elif related_id not in ids:
                errors.append(
                    f'Term "{entry.term}": related term '
                    f"{related_id!r} does not exist."
                )

    if errors:
        raise GlossaryValidationError(errors)

    return terms


def _required_string(
    raw_term: dict[str, Any],
    field: str,
    label: str,
    errors: list[str],
) -> str:
    value = raw_term.get(field)

    if not isinstance(value, str) or not value.strip():
        errors.append(
            f"{label}: '{field}' is required and must "
            "be a non-empty string."
        )
        return ""

    return value.strip()


def _optional_string(
    raw_term: dict[str, Any],
    field: str,
    label: str,
    errors: list[str],
) -> str | None:
    value = raw_term.get(field)

    if value is None:
        return None

    if not isinstance(value, str):
        errors.append(
            f"{label}: '{field}' must be a string when provided."
        )
        return None

    stripped = value.strip()
    return stripped or None


def _string_list(
    raw_term: dict[str, Any],
    field: str,
    label: str,
    errors: list[str],
) -> list[str]:
    value = raw_term.get(field)

    if value is None:
        return []

    if not isinstance(value, list):
        errors.append(
            f"{label}: '{field}' must be a list when provided."
        )
        return []

    values: list[str] = []

    for item in value:
        if not isinstance(item, str) or not item.strip():
            errors.append(
                f"{label}: every value in '{field}' must "
                "be a non-empty string."
            )
            continue

        values.append(item.strip())

    return values


def render_glossary(
    terms: list[GlossaryTerm],
) -> str:
    """Render the complete generated glossary MDX page."""
    sorted_terms = sorted(
        terms,
        key=lambda item: item.term.casefold(),
    )

    by_id = {
        term.id: term
        for term in sorted_terms
    }

    lines = [
        "---",
        "id: Gloss",
        (
            "subtitle: Look up the terms used throughout "
            "the Python RAG Service documentation"
        ),
        "title: Glossary",
        "content_type: general_reference",
        (
            "description: Look up concise definitions for RAG, "
            "retrieval, indexing, evaluation, API, and "
            "project-specific terms used throughout the "
            "documentation."
        ),
        "lifecycle_status: draft",
        "topics: [topic-terminology]",
        "max-toc-depth: 3",
        "last_modified: <generated>",
        "---",
        "",
        GENERATED_NOTE,
        "",
        (
            "The glossary defines terms used throughout "
            "the Python RAG Service and its documentation."
        ),
    ]

    current_letter: str | None = None

    for term in sorted_terms:
        letter = term.term[0].upper()

        if letter != current_letter:
            lines.extend(
                [
                    "",
                    f"## {letter}",
                ]
            )
            current_letter = letter

        lines.extend(
            [
                "",
                f"### {term.term}",
                "",
                term.definition,
            ]
        )

        if term.example:
            lines.extend(
                [
                    "",
                    "#### Example",
                    "",
                    term.example,
                ]
            )

        if term.aliases:
            aliases = ", ".join(term.aliases)

            lines.extend(
                [
                    "",
                    f"**Also known as:** {aliases}",
                ]
            )

        if term.related_terms:
            related = sorted(
                (
                    by_id[related_id]
                    for related_id in term.related_terms
                ),
                key=lambda item: item.term.casefold(),
            )

            links = ", ".join(
                (
                    f"[{_escape_link_text(item.term)}]"
                    f"(#{_heading_slug(item.term)})"
                )
                for item in related
            )

            lines.extend(
                [
                    "",
                    f"**Related terms:** {links}",
                ]
            )

    return "\n".join(lines).rstrip() + "\n"


def render_vale_vocabulary(
    terms: list[GlossaryTerm],
) -> str:
    """Render canonical terms and accepted aliases for Vale."""
    values = {
        value
        for term in terms
        for value in (
            term.term,
            *term.aliases,
        )
    }

    if not values:
        return ""

    return (
        "\n".join(
            sorted(
                values,
                key=str.casefold,
            )
        )
        + "\n"
    )


def _heading_slug(value: str) -> str:
    """Create the fragment used for generated heading links."""
    slug = value.casefold()
    slug = re.sub(r"[^\w\s-]", "", slug)
    slug = re.sub(r"[\s_-]+", "-", slug)

    return slug.strip("-")


def _escape_link_text(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace("[", "\\[")
        .replace("]", "\\]")
    )


def write_if_changed(path: Path, content: str) -> str:
    """Write a generated file only when its content has changed."""
    if path.is_file():
        existing = path.read_text(encoding="utf-8")

        if existing == content:
            return "Unchanged"

        status = "Updated"
    else:
        status = "New"

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )
    path.write_text(
        content,
        encoding="utf-8",
    )

    return status


def write_outputs(
    glossary: str,
    vale_vocabulary: str,
) -> tuple[str, str]:
    """Write generated outputs and return their change status."""
    glossary_status = write_if_changed(
        GLOSSARY_PATH,
        glossary,
    )
    vale_status = write_if_changed(
        VALE_ACCEPT_PATH,
        vale_vocabulary,
    )

    return glossary_status, vale_status

def check_generated_file(
    path: Path,
    expected_content: str,
) -> str | None:
    """Return an error when a generated file is missing or stale."""
    if not path.is_file():
        return f"Missing generated file: {path}"

    actual_content = path.read_text(
        encoding="utf-8",
    )

    if actual_content != expected_content:
        return f"Generated file is out of date: {path}"

    return None

def check_outputs(
    glossary: str,
    vale_vocabulary: str,
    *,
    glossary_path: Path = GLOSSARY_PATH,
    vale_path: Path = VALE_ACCEPT_PATH,
) -> list[str]:
    """Check whether committed generated outputs are current."""
    errors: list[str] = []

    glossary_error = check_generated_file(
        glossary_path,
        glossary,
    )

    if glossary_error:
        errors.append(glossary_error)

    vale_error = check_generated_file(
        vale_path,
        vale_vocabulary,
    )

    if vale_error:
        errors.append(vale_error)

    return errors

def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate or validate glossary-derived files."
        )
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Check that generated files are current "
            "without modifying them."
        ),
    )

    args = parser.parse_args()

    try:
        terms = load_glossary(SOURCE_PATH)
        glossary = render_glossary(terms)
        vale_vocabulary = render_vale_vocabulary(terms)

    except FileNotFoundError as exc:
        print(
            str(exc),
            file=sys.stderr,
        )
        return 1

    except GlossaryValidationError as exc:
        print(
            "Glossary validation failed:\n",
            file=sys.stderr,
        )

        for error in exc.errors:
            print(
                f"- {error}",
                file=sys.stderr,
            )

        print(
            "\nNo files were generated.",
            file=sys.stderr,
        )
        return 1

    if args.check:
        errors = check_outputs(
            glossary,
            vale_vocabulary,
        )

        if errors:
            print(
                "Generated glossary outputs are out of date:\n",
                file=sys.stderr,
            )

            for error in errors:
                print(
                    f"- {error}",
                    file=sys.stderr,
                )

            print(
                "\nRun this command to regenerate them:\n"
                "uv run python scripts/generate_glossary.py",
                file=sys.stderr,
            )

            return 1

        print(
            "Generated glossary and Vale vocabulary "
            "are current."
        )
        return 0

    glossary_status, vale_status = write_outputs(
        glossary,
        vale_vocabulary,
    )

    print(f"Glossary terms: {len(terms)}")
    print(
        f"{glossary_status}: "
        f"{GLOSSARY_PATH.relative_to(REPO_ROOT)}"
    )
    print(
        f"{vale_status}: "
        f"{VALE_ACCEPT_PATH.relative_to(REPO_ROOT)}"
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())